---
- hosts: se
  gather_facts: no

  vars_files:
    - "vars/params.yml"

  tasks:

    # - name: Create a directory
    #   file:
    #     path: .ssh
    #     state: directory
    #
    # - name: copy ssh keys for putty
    #   copy:
    #     src: "{{ ssh.authorizedKeyFile }}"
    #     dest: .ssh/{{ ssh.authorizedKeyFile | basename }}
    #   ignore_errors: yes

    - name: Update repositories cache and install a list of package
      become: true
      apt:
        name: "{{ item }}"
        update_cache: yes
      ignore_errors: yes
      loop: "{{ packageList }}"
      when: packageList is defined
      tags:
        - se


    - name: Upgrade all packages to the latest version
      become: true
      apt:
        name: "*"
        state: latest
        force_apt_get: True
      ignore_errors: yes
      tags:
        - se
