---
- hosts: controller
  gather_facts: no

  vars_files:
    - "vars/params.yml"

  tasks:

    # - name: Retrieve Avi version
    #   set_fact:
    #     aviVersion: "{{ avi.controller.binFile.split('/')[-1].split('-')[1] }}"
    #   tags:
    #     - creds
    #   when: avi.version is not defined

    - name: Write Avi version in a file
      copy:
        content: "api_version: {{ avi.controller.binFile.split('/')[-1].split('-')[1] }}"
        dest: "{{ avi.versionFile }}"
      tags:
        - version
      delegate_to: 127.0.0.1
      run_once: true
