ssh:
  authorizedKeyFile: /home/avi/ssh/authorized_keys

avi:
  controller:
    cpu: 6
    mem: 16
    #binFile: /home/avi/bin/avi/docker_install-18.1.3-9144.tar.gz
    #binFile: /home/avi/bin/avi/docker_install-18.1.5-9249.tar.gz
    #googleId: 1dGdniUH4_XN1JqoZ12lu5zSVnoYHa-D6 v18.1.5
    #googleId: 18ytTgU2pBs36sCuE_gLDXjdtFkf8K4l- v17.2.14
    #binFile: /home/avi/bin/avi/docker_install-17.2.14-9128.tar.gz
    googleDrive: false
    googleId: 18ytTgU2pBs36sCuE_gLDXjdtFkf8K4l-
    #binFile: /home/avi/bin/avi/docker_install-17.2.14-9128.tar.gz
    binFile: /home/avi/bin/avi/docker_install-18.2.8-9205.tar.gz
  credentialsFile:
    - ../aviBootstrap/vars/creds.yml
  #version: 17.2.14
  username: admin
  password: Avi2020
  floatingIp: 192.168.36.250
  controllerFile:
    - ../aviBootstrap/vars/controller.json
  cloud: lsc


packageList:
  - docker.io
