# ssh:
#   authorizedKeyFile: /home/avi/ssh/authorized_keys

avi:
  versionFile: ../aviLscBootstrap/vars/aviVersion.yml
  controller:
    cpu: 6
    mem: 16
    binFile: /home/avi/bin/avi/docker_install-18.2.9-9147.tar.gz

packageList:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
keyUrl:
  - https://download.docker.com/linux/ubuntu/gpg
repoUrl:
  - deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ hostvars[inventory_hostname].ansible_distribution_release }} stable
dockerVersion: 5:18.09.5~3-0~ubuntu
dockerPackages:
  - docker-ce-cli={{ dockerVersion }}-{{ hostvars[inventory_hostname].ansible_distribution_release }}
  - docker-ce={{ dockerVersion }}-{{ hostvars[inventory_hostname].ansible_distribution_release }}
  - containerd.io
dockerUsers:
  - avi
